# Generated by Django 5.2.1 on 2025-06-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=20)),
                ('narxi', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('familya', models.CharField(max_length=20)),
                ('yosh', models.PositiveSmallIntegerField(default=19)),
            ],
        ),
        migrations.CreateModel(
            name='Xizmat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Xizmatturi', models.CharField(max_length=50)),
                ('narxi', models.PositiveBigIntegerField(max_length=20)),
                ('ishsoati', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
