# Generated by Django 5.2.1 on 2025-06-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sodda_sahifalar_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xizmat',
            old_name='Xizmatturi',
            new_name='xizmatturi',
        ),
        migrations.AddField(
            model_name='maxsulot',
            name='tavsifi',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xizmat',
            name='xizmatnomi',
            field=models.CharField(default=2001, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maxsulot',
            name='narxi',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='narxi',
            field=models.BigIntegerField(),
        ),
    ]
