# Generated by Django 5.2.1 on 2025-06-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sodda_sahifalar_app', '0002_rename_xizmatturi_xizmat_xizmatturi_maxsulot_tavsifi_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Talaba',
        ),
        migrations.AddField(
            model_name='maxsulot',
            name='tasviri',
            field=models.ImageField(default='2025', upload_to=''),
            preserve_default=False,
        ),
    ]
